### ISSUE TITLE
Issues installing ukbpheno

### ISSUE THREAD

**Issue by akhilpampana** [niekverw/ukbpheno#1]
Hello,

I am trying to install it as suggested by step by step process in the paper (https://star-protocols.cell.com/protocols/1733#before-you-begin). I am using the same version of R and I am having a hard time installing the software. I am getting this error:
'ERROR: dependency 'nloptr' is not available for package 'lme4'

1.) Can you let me know if there is a workaround for this issue? 
2.) Also can you let me know if you had faced the issue before?
3.) If I want to install it in the latest r studio, what are the recommendations u suggest for me to install this package?

Regards
Akhil

**Comment by lea1010** [comment]
Hi Akhil,
1) Could you paste the full error message & also run sessionInfo()? 
2) I had similar issue for installing dependencies from CRAN using older R version (3.6). There was a line among the error message which said:
"dependency “xx” is not available (for R version x.x.x)"
It can be solved by specifying the version of package compatible for the corresponding R version (see https://stackoverflow.com/questions/62900525/install-lme4-from-cran-on-ubuntu).
3) There is no requirement on RStudio version for the package itself so you should be able to use the package in the latest version (just make sure your R version meet the requirement of RStudio, see https://www.rstudio.com/products/rstudio/download/#download) .

**Comment by akhilpampana** [comment]
1.) Error
***** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/data/user/home/apampana/R/x86_64-pc-linux-gnu-library/4.1/nloptr/libs/nloptr.so':
  libgfortran.so.5: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package 'lme4'
* removing '/data/user/home/apampana/R/x86_64-pc-linux-gnu-library/4.1/lme4'
ERROR: dependency 'lme4' is not available for package 'pbkrtest'
* removing '/data/user/home/apampana/R/x86_64-pc-linux-gnu-library/4.1/pbkrtest'
ERROR: dependencies 'pbkrtest', 'lme4' are not available for package 'car'
* removing '/data/user/home/apampana/R/x86_64-pc-linux-gnu-library/4.1/car'
ERROR: dependency 'car' is not available for package 'rstatix'
* removing '/data/user/home/apampana/R/x86_64-pc-linux-gnu-library/4.1/rstatix'
ERROR: dependency 'rstatix' is not available for package 'ggpubr'
* removing '/data/user/home/apampana/R/x86_64-pc-linux-gnu-library/4.1/ggpubr'

The downloaded source packages are in
        '/local/RtmpZhljpg/downloaded_packages'
v  checking for file '/local/RtmpZhljpg/remotes1609744b661d9/niekverw-ukbpheno-34071d3/DESCRIPTION' ...
-  preparing 'ukbpheno':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'ukbpheno_0.0.0.9000.tar.gz'
   
Installing package into '/data/user/home/apampana/R/x86_64-pc-linux-gnu-library/4.1'
(as 'lib' is unspecified)
ERROR: dependencies 'data.table', 'ggpubr' are not available for package 'ukbpheno'
* removing '/data/user/home/apampana/R/x86_64-pc-linux-gnu-library/4.1/ukbpheno'
Warning messages:
1: In i.p(...) : installation of package 'nloptr' had non-zero exit status
2: In i.p(...) :
  installation of package 'data.table' had non-zero exit status
3: In i.p(...) : installation of package 'lme4' had non-zero exit status
4: In i.p(...) :
  installation of package 'pbkrtest' had non-zero exit status
5: In i.p(...) : installation of package 'car' had non-zero exit status
6: In i.p(...) :
  installation of package 'rstatix' had non-zero exit status
7: In i.p(...) : installation of package 'ggpubr' had non-zero exit status
8: In i.p(...) :
  installation of package '/scratch/local/RtmpZhljpg/file160976b77d404/ukbpheno_0.0.0.9000.tar.gz' had non-zero exit status**


**> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /data/rc/apps/rc/software/OpenBLAS/0.2.20-GCC-6.4.0-2.28/lib/libopenblas_haswellp-r0.2.20.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.7.1          prettyunits_1.1.1 withr_2.5.0       rprojroot_2.0.3  
 [5] crayon_1.5.1      R6_2.5.1          lifecycle_1.0.1   magrittr_2.0.3   
 [9] rlang_1.0.3       cachem_1.0.6      cli_3.3.0         curl_4.3.2       
[13] remotes_2.4.2     fs_1.5.2          callr_3.7.0       ellipsis_0.3.2   
[17] devtools_2.4.3    tools_4.1.2       glue_1.6.2        purrr_0.3.4      
[21] pkgload_1.3.0     fastmap_1.1.0     compiler_4.1.2    processx_3.6.1   
[25] pkgbuild_1.3.1    sessioninfo_1.2.2 memoise_2.0.1     usethis_2.1.5**    


2.) I will check the installation methods suggested by you. Thank you so much. the lme4 installation is the main issue I am facing. I am trying to replicate as in the star protocol paper. 

3.) I am running it in the Linux version of R in the HPC cluster we have access to.

Please do let me know if it can be run on the HPC cluster?

**Comment by akhilpampana** [comment]
Thank you so much , your suggestion from point 2 helped me a lot. I could able to install packages. for some reason, nloptr latest version is creating issues with the installation. I hope its not an important package for the extraction process ?

**Comment by lea1010** [comment]
1) It seems that you are missing/R cannot find `libgfortran.so.5`. If it is missing, you can install it by:
`yum install libgfortran`
See https://stackoverflow.com/questions/45293476/how-to-install-fortran-dev-package-using-sudo-yum-install for details.
2) lme4 cannot be installed probably because of 1) 
3) Yes you can run the package on HPC as well.
4) Extraction process works fine with older versions of nloptr.

Great that the suggestion worked!

**Comment by akhilpampana** [comment]
Thank you for the suggestions. I have FORTRAN as a prebuilt package in HPC so I loaded that to resolve the issue. Thank you so much for helping me out. I will keep you posted if any questions again.

**Comment by akhilpampana** [comment]
May I know how did u generate phenotypes definitions as suggested in extdata? I have phenotypes with icd codes, will it help in generating phenotypes as per ukbpheno? I want to generate based on definitions from this paper https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.118.035774 . Thank you so much for your help.

**Comment by lea1010** [comment]
You can fill in the definition table with the diagnosis codes provided in the Supplemental Table 1 in their study and then generate the phenotypes at once using ukbpheno (c.f. session "Generate phenotypes in batch").

I will close this issue as the installation problem is now resolved.
