### ISSUE TITLE
ukbpheno 2 questions

### ISSUE THREAD

**Issue by zhangpicb** [niekverw/ukbpheno#3]
Hi @lea1010 @niekverw

Thanks for your beautiful code !

I meet 2 problems when I use ukbpheno example data to learn how to use ukbpheno.

1.How to make Input file ``` definitions_melanoma_ukbpheno.tsv``` to function  ```read_defnition_table```? 
I make  a one row ``` tsv ``` file,and get an error when I input this file to  ```read_defnition_table```.
And I use ``` rbind ```  bind  ``` definitions_melanoma_ukbpheno.tsv```and my one row tsv file. ```read_defnition_table``` can run sucessfully.

2.How to filter  samples by ``` Physical measures ⏴ [Assessment Centre](https://biobank.ndph.ox.ac.uk/showcase/label.cgi?id=100000)```?For  example,how filter  samples by this [ [questionhttps://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=5181 ?
](https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=5181)](https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=5181)?

Thanks in advanced!

**Comment by lea1010** [comment]
Hi @zhangpicb ,
1. Perhaps there is no header in your `definitions_melanoma_ukbpheno.tsv` ?
2. One possible solution would be to extract that field 5181 with `read_ukb_tabdata()` and then select individuals passing your desired threshold(s).

**Comment by jasminegr** [comment]
Thank you for the package!
I've also encountered an error when using the `read_definition_table` function: `Error in value[[jvseq[[jjj]]]] : subscript out of bounds`. I created a tsv file based on the pre-filled template you've provided. 
I think part of the issue might be that in the `read_definition_table` function on line 2 `dfDefinitions <- data.table::fread(fdefinitions, colClasses = "character", data.table = FALSE))` `fdefinitions` should be `f.definitions` as specified by the function? In the current version of the function, the template table is consistently read in. If I change `fdefinitions` to my table, the "subscript out of bounds" issue appears.

**Comment by lea1010** [comment]
Hi @jasminegr,
Many thanks for pointing that out!
Indeed there was a typo in the function `read_definition_table()` which is now fixed.

**Comment by lea1010** [comment]
My apologies and thanks for helping in tracking the issues which are both fixed now.
"subscript out of bounds issue" arises when there is no rows to process in  `parseIncludeExcludeCol()` / there is no composite phenotype with inclusion/exclusion criteria. I have modified the function to skip the parsing step in this scenario.
Many thanks @zhangpicb & @jasminegr for bringing this up!
