### ISSUE TITLE
convert_nurseinterview_to_episodedata()

### ISSUE THREAD

**Issue by jasminegr** [niekverw/ukbpheno#4]
Hi, I am running your package using my own data definition table and have come across the following error when trying to harmonise the data using `harmonize_ukb_data`:

```
Convert self-reported data
 ->Self-reported cancer codes (field 20001)
Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index
```

It's most likely coming from the `convert_nurseinterview_to_episodedata` function. I was wondering whether you know why this is happening and how it could be resolved? 

Thank you!

**Comment by lea1010** [comment]
Hi @jasminegr ,

I suspect this may be a same issue as the previous one that the function is trying to subset an empty table (so in this case columns for field 20001 & field 20006). Do you have these columns in your dataset?  If so, I can add the lines to check & skip the corresponding steps within the `harmonize_ukb_data()` if those fields are not present.

**Comment by jasminegr** [comment]
Thanks @lea1010, I have both data fields in my dataset. I think it might have to do with the `grepl` functions in `convert_nurseinterview_to_episodedata` ? If I modify for example `visitdatefields = names(df)[grepl(paste0("[^0-9]", field_visit_date, "[^0-9]"), names(df))]` to `visitdatefields = names(df)[grepl(paste0(field_visit_date, "[^0-9]"), names(df))]`, the columns are correctly selected and the table isn't empty. However I'm unable to check whether this resolves the error message.. Thanks in advance!

**Comment by lea1010** [comment]
Hi @jasminegr , 

Can you show some column names in your .tab file? (the .tab file generated from `ukbconv ukb23456.enc_ukb r` )
More specifically, are they in the form of  "f.xxxxx.y.z"? 

`visitdatefields = names(df)[grepl(paste0("[^0-9]", field_visit_date, "[^0-9]"), names(df))] ` will grep field names like " _**f.**_ 53.0.0" 
while `visitdatefields = names(df)[grepl(paste0(field_visit_date, "[^0-9]"), names(df))]` will grep field names like "53.0.0" but also fields like "24153.0.0". So it is necessary to retain the `"[^0-9]"` in the front.

**Comment by niekverw** [comment]
@lea1010 We could implement a check for the expected fields at the top of the function?

**Comment by jasminegr** [comment]
Yes that's probably what is causing the issue - my file column names are written as "xxxxx.y.z" but I'll try to convert them to "f.xxxxx.y.z". Thank you for the information!

**Comment by jasminegr** [comment]
My outcome definitions are actually only based on HES and GP data (not self-reported / death registry data). I was wondering whether there could be the option to skip the `convert_nurseinterview_to_episodedata` functions when running `harmonize_ukb_data` ? Only a suggestion - thanks a lot!

**Comment by niekverw** [comment]
Did you use this command to convert the UKB data into R format?  `ukbconv ukb12345.enc_ukb r` , this should give the right column headers, more easily readable by R (together with the html file). 


You can run this function line by line  and comment out the parts that use the UKB tabular data: https://github.com/niekverw/ukbpheno/blob/master/R/prepare_ukb_data.R#L73. It is a big part of the package, we can add an option to skip it, but am not sure if that is really helpful for everyone.

**Comment by lea1010** [comment]
I have added a check in `harmonize_ukb_data` 
@jasminegr if you are only taking HES and GP data I think indeed it is easier to use the individual parsing functions
(`read_hesin_data` & `read_gp_*_data` ) / comment out the parts in the wrapper function like @niekverw suggested. 
I will try to add some info on that in the wiki.

**Comment by jasminegr** [comment]
Thank you @niekverw and @lea1010 - that worked!
