### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by bhrw** [niekverw/ukbpheno#5]
Hello.
I am getting an error in the syntax for dfDefinitions:

dfDefinitions_processed_expanded<-read_definition_table(fdefinitions,fdata_setting,extdata_dir)

Read from codings for READ2 from C:/Users/BHRW/Documents/R/win-library/4.1/ukbpheno/extdata/gpclinical.read2.code
Error in `stringr::regex()`:
! `ignore_case` must be `TRUE` or `FALSE`, not a <data.table/data.frame> object.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error in `stringr::regex()`:
! `ignore_case` must be `TRUE` or `FALSE`, not a <data.table/data.frame> object.
---
Backtrace:
 1. ukbpheno::read_definition_table(...)
 2. ukbpheno::check_dfDefinitions_codes(...)
 3. base::lapply(...)
 4. ukbpheno (local) FUN(X[[i]], ...)
 8. stringr::regex(ignore_case = ignore.case)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Error in `stringr::regex()`:
! `ignore_case` must be `TRUE` or `FALSE`, not a <data.table/data.frame> object.
---
Backtrace:
     x
  1. \-ukbpheno::read_definition_table(...)
  2.   \-ukbpheno::check_dfDefinitions_codes(...)
  3.     \-base::lapply(...)
  4.       \-ukbpheno (local) FUN(X[[i]], ...)
  5.         +-stringr::str_detect(...)
  6.         | \-stringr:::check_lengths(string, pattern)
  7.         |   \-vctrs::vec_size_common(...)
  8.         \-stringr::regex(ignore_case = ignore.case)
  9.           \-stringr:::check_bool(ignore_case)
 10.             \-stringr:::stop_input_type(...)
 11.               \-rlang::abort(message, ..., call = call, arg = arg)
> 

Can you advise??

Many thanks.
Bruce

**Comment by lea1010** [comment]
Hi @bhrw 
Apologies for the late reply. Could you reinstall the package and try again? 
It should be fixed now.

**Comment by bhrw** [comment]
Thanks, Ming, indeed this is fixed now.

Best wishes
Bruce


Van: Ming Wai Yeung ***@***.***>
Verzonden: Tuesday, 6 December 2022 18:47
Aan: niekverw/ukbpheno ***@***.***>
CC: Wolffenbuttel, BHR (int) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [niekverw/ukbpheno] Error message (Issue #5)


Hi @bhrw<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbhrw&data=05%7C01%7Cbwo%40umcg.nl%7C386eff305a6147dec5b808dad7b1d5fa%7C335122f9d4f44d67a2fccd6dc20dde70%7C0%7C0%7C638059456040900207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HSuCD9BJnbltMr0jjFLEnJkXDoZQw3T%2B3AMem5v%2FO28%3D&reserved=0>
Apologies for the late reply. Could you reinstall the package and try again?
It should be fixed now.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fniekverw%2Fukbpheno%2Fissues%2F5%23issuecomment-1339747423&data=05%7C01%7Cbwo%40umcg.nl%7C386eff305a6147dec5b808dad7b1d5fa%7C335122f9d4f44d67a2fccd6dc20dde70%7C0%7C0%7C638059456040900207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kkVcOAWIVcoGrJUCQdt1k%2BTGRQv0A4z6PFwODCeClBc%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZNUAE2WOEXI5353YI33ELWL53YDANCNFSM6AAAAAASS5CZJQ&data=05%7C01%7Cbwo%40umcg.nl%7C386eff305a6147dec5b808dad7b1d5fa%7C335122f9d4f44d67a2fccd6dc20dde70%7C0%7C0%7C638059456040900207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9pf28FyMdKxJw%2FTzrlk0NTAF7QE%2BPh1rKukY42IEBf4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

________________________________
De inhoud van dit bericht is vertrouwelijk en alleen bestemd voor de geadresseerde(n). Anderen dan de geadresseerde(n) mogen geen gebruik maken van dit bericht, het niet openbaar maken of op enige wijze verspreiden of vermenigvuldigen. Het UMCG kan niet aansprakelijk gesteld worden voor een incomplete aankomst of vertraging van dit verzonden bericht.

The contents of this message are confidential and only intended for the eyes of the addressee(s). Others than the addressee(s) are not allowed to use this message, to make it public or to distribute or multiply this message in any way. The UMCG cannot be held responsible for incomplete reception or delay of this transferred message.
